#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f program_counter.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace program_counter.sv --exe program_counter_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vprogram_counter.mk Vprogram_counter

# run executable simulation file
obj_dir/Vprogram_counter