#!/bin.sh

# create vbuddy.cfg with the usb port that it is connected to
ls /dev/tty.usb* > vbuddy.cfg

filename=$1

# cleanup
# rm --> remove/delete
rm -rf obj_dir
# rm - rf --> recursively force remove what is in file
rm -f ${filename}.vcd

# run Verilator to translate Verilog into c++, including c++ testbench
verilator -Wall --cc --trace ${filename}.sv --exe ${filename}_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f V${filename}.mk V${filename}

#run executable simulation firl
obj_dir/V${filename}